// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyBZt5nSQAexttfpsPnDYRduXWzwg_8whKk',
  //   appId: '1:766557129839:web:dbd83ceab98be5f901919a',
  //   messagingSenderId: '36406438773',
  //   projectId: 'hashingloginapp',
  //   authDomain: 'fiveguysotp.firebaseapp.com',
  //   storageBucket: 'hashingloginapp.appspot.com',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZt5nSQAexttfpsPnDYRduXWzwg_8whKk',
    appId: '1:36406438773:android:6d557f00cfa6812257413c',
    messagingSenderId: '36406438773',
    projectId: 'hashingloginapp',
    storageBucket: 'hashingloginapp.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBZt5nSQAexttfpsPnDYRduXWzwg_8whKk',
  //   appId: '1:766557129839:ios:7c3624a110b7525601919a',
  //   messagingSenderId: '36406438773',
  //   projectId: 'hashingloginapp',
  //   storageBucket: 'hashingloginapp.appspot.com',
  //   iosBundleId: 'com.example.fiveguysotp',
  // );

}